### ISSUE TITLE
Error for open url "https://github1s.com/microsoft/vscode" in chrome browser

### ISSUE THREAD

**Issue by fjibj** [conwnet/github1s#11]
ERR The Web Worker Extension Host did not start in 10s: Error: The Web Worker Extension Host did not start in 10s
    at https://github1s.com/static-62eb1a5/vscode/vs/workbench/workbench.web.api.js:4802:845
workbench.web.api.js:1727   ERR ENOPRO: No file system provider found for resource 'github1s://microsoft%2Bvscode%2Bhead/'
    at _.withProvider (https://github1s.com/static-62eb1a5/vscode/vs/workbench/workbench.web.api.js:1747:504)
    at async _.doWatch (https://github1s.com/static-62eb1a5/vscode/vs/workbench/workbench.web.api.js:1759:648)
workbench.web.api.js:1727   ERR No file system provider found for resource 'github1s://microsoft%2Bvscode%2Bhead/': ENOPRO: No file system provider found for resource 'github1s://microsoft%2Bvscode%2Bhead/'
    at _.withProvider (https://github1s.com/static-62eb1a5/vscode/vs/workbench/workbench.web.api.js:1747:504)
    at async _.doResolveFile (https://github1s.com/static-62eb1a5/vscode/vs/workbench/workbench.web.api.js:1748:554)
    at async _.resolve (https://github1s.com/static-62eb1a5/vscode/vs/workbench/workbench.web.api.js:1748:279)
    at async Promise.all (index 0)

**Comment by xcv58** [comment]
I couldn't reproduce the same bug,

![image](https://user-images.githubusercontent.com/503123/107266906-06662f80-69fb-11eb-8949-d94819e5e44d.png)

Could you please double check the following?

1. You can access https://github.com/microsoft/vscode with no issue?
2. You are not rate limited by GitHub?

**Comment by JeffreyCA** [comment]
It happens with Safari only.

**Comment by xcv58** [comment]
I couldn't reproduce on Safari as well, the Safari version:

![image](https://user-images.githubusercontent.com/503123/107479585-2f3c1100-6b30-11eb-882c-d23cd52d463e.png)

**Comment by JeffreyCA** [comment]
Strange, after refreshing the page I don't get the error anymore.

**Comment by xcv58** [comment]
Close since couldn't reproduce.

Please reopen if you could consistently reproduce the issue.
